/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atenda.vista;

import atenda.modelo.Iva;
import atenda.modelo.Producto;
import atenda.modelo.LineaPedido;
import atenda.controlador.ModeloDAO;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elias
 */
public class VentasPanel extends javax.swing.JPanel {

    /**
     * Creates new form VentasPanel
     */
    private ModeloDAO pedidoDAO;
    private ModeloDAO userDao;

    public VentasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hastaFechaChosser = new com.toedter.calendar.JDateChooser();
        desdeFechaChosser = new com.toedter.calendar.JDateChooser();
        botonTraerPedidos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetallePorPedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        etiquetaFacturacion = new javax.swing.JLabel();
        etiquetaDescuentos = new javax.swing.JLabel();
        etiquetaCostos = new javax.swing.JLabel();
        etiquetaBeneficio = new javax.swing.JLabel();
        etiquetaIva = new javax.swing.JLabel();

        jLabel1.setText("Dende");

        jLabel2.setText("Ata");

        botonTraerPedidos.setText("Ver pedidos");
        botonTraerPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTraerPedidosMouseClicked(evt);
            }
        });

        jLabel3.setText("Listaxe de pedidos");

        jLabel4.setText("Detalles de pedido");

        tablaDetallePorPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Uds", "Prezo", "Desc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDetallePorPedido);

        jLabel5.setText("Informe dos Pedidos");

        jLabel6.setText("Facturación (Prezo final de venta)");

        jLabel7.setText("Descontos (sobre prezo producto):");

        jLabel8.setText("Costes:");

        jLabel9.setText("Beneficio=facturación - costes");

        jLabel10.setText("IVA:");

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonTraerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desdeFechaChosser, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(hastaFechaChosser, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(etiquetaDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiquetaIva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(etiquetaCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(etiquetaBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiquetaFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desdeFechaChosser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hastaFechaChosser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonTraerPedidos)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(etiquetaDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(etiquetaIva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonTraerPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTraerPedidosMouseClicked
        // TODO add your handling code here:

        Date fechaDesde = desdeFechaChosser.getDate();
        Date fechaHasta = hastaFechaChosser.getDate();
        DefaultTableModel modelDetallesPedidoPorPedido = (DefaultTableModel) tablaDetallePorPedido.getModel();
        modelDetallesPedidoPorPedido.setRowCount(0);
        
        
        
        pedidoDAO = new ModeloDAO();
        userDao = new ModeloDAO();
        // Verificar que las fechas sean válidas
        if (fechaDesde == null || fechaHasta == null) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir las fechas a objetos java.sql.Date
        java.sql.Date fechaDesdeSQL = new java.sql.Date(fechaDesde.getTime());
        java.sql.Date fechaHastaSQL = new java.sql.Date(fechaHasta.getTime());

        // Obtener los registros de pedidos dentro del rango de fechas
        List<String> pedidoRecords = pedidoDAO.getPedidoRecordsPorFecha(fechaDesdeSQL, fechaHastaSQL);
        double sumaFacturacion = pedidoDAO.sumarCosteLineaPedidoPorFecha(fechaDesdeSQL, fechaHastaSQL);
        double sumaDesconto = pedidoDAO.sumarDescontoLineaPedidoPorFecha(fechaDesdeSQL, fechaHastaSQL);
        double sumaCostes = pedidoDAO.multiplicarUnidadesCosteLineaPedidoPorFecha(fechaDesdeSQL, fechaHastaSQL);
        double beneficio =  sumaFacturacion - sumaCostes;
        double ivaAcumulado = pedidoDAO.sumarIvaLineaPedidoPorFecha(fechaDesdeSQL, fechaHastaSQL);

        // Poblar la tabla tablaPedidos con los registros obtenidos
        DefaultTableModel modelPedidos = (DefaultTableModel) tablaPedidos.getModel();
        modelPedidos.setRowCount(0); // Limpiar filas existentes

        for (String record : pedidoRecords) {
            String[] parts = record.split(" ");
            if (parts.length >= 3) {
                String idPedido = parts[0];
                String fecha = parts[1];
                String idCliente = parts[parts.length - 1];
                int idClienteInt = Integer.parseInt(idCliente);
                String dependente = userDao.obtenerNombreConId(idClienteInt);

                Object[] rowData = {idPedido, fecha, dependente};
                modelPedidos.addRow(rowData);
            }
        }
        
        etiquetaFacturacion.setText(String.valueOf(sumaFacturacion));
        etiquetaDescuentos.setText(String.valueOf(sumaDesconto));
        etiquetaCostos.setText(String.valueOf(sumaCostes));
        etiquetaBeneficio.setText(String.valueOf(beneficio));
        etiquetaIva.setText(String.valueOf(ivaAcumulado));
        
        
    }//GEN-LAST:event_botonTraerPedidosMouseClicked

    private void tablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPedidosMouseClicked
        // TODO add your handling code here:
        int selectedRow = tablaPedidos.getSelectedRow();
        int idPedido = Integer.parseInt(tablaPedidos.getValueAt(selectedRow, 0).toString());
        String fecha = tablaPedidos.getValueAt(selectedRow, 1).toString();

        DefaultTableModel model = (DefaultTableModel) tablaDetallePorPedido.getModel();
        model.setRowCount(0); // Limpiar filas existentes

        List<LineaPedido> lineasPedido = pedidoDAO.obtenerLineasPedidoPorIdPedido(idPedido);
        for (LineaPedido lineaPedido : lineasPedido) {
            String nombreProducto = pedidoDAO.obtenerNombreProductoPorId(lineaPedido.getId_producto());
            int unidades = lineaPedido.getUnidades();
            double precio = lineaPedido.getPrezo();
            int descuento = lineaPedido.getDesconto();
            ModeloDAO prodDAO = new ModeloDAO();
            Producto prod = new Producto();
            try {
                prod = prodDAO.getProductoByNombre(nombreProducto);
            } catch (SQLException ex) {
                Logger.getLogger(DevolucionPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Iva iva = prod.getIva();
            double ivaAsignado = 0;

            if (iva.equals("TIPO_REDUCIDO")) {
                ivaAsignado = 10 / 100.0;
            } else if (iva.equals("TIPO_XERAL")) {
                ivaAsignado = 21 / 100.0;
            } else if (iva.equals("TIPO_SUPERREDUCIDO")) {
                ivaAsignado = 4 / 100.0;
            }
            Object[] rowData = {nombreProducto, unidades, precio, descuento, ivaAsignado};
            model.addRow(rowData);
        }

    }//GEN-LAST:event_tablaPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTraerPedidos;
    private com.toedter.calendar.JDateChooser desdeFechaChosser;
    private javax.swing.JLabel etiquetaBeneficio;
    private javax.swing.JLabel etiquetaCostos;
    private javax.swing.JLabel etiquetaDescuentos;
    private javax.swing.JLabel etiquetaFacturacion;
    private javax.swing.JLabel etiquetaIva;
    private com.toedter.calendar.JDateChooser hastaFechaChosser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDetallePorPedido;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
